project:
  type: book
  output-dir: docs
  post-render: meta/fix_page_breaks.py

book:
  title: "A Characterization of the Australian Financial Assistance Grants System"
  author: ["S Pulick", "E Ritchie"]
  date: today
  reader-mode: false
  site-url: https://spulick.github.io/fa_grants/
  search: true

  chapters:
    - index.qmd
    - intro.qmd
  # - methodology.qmd
    - part: "Jurisdictions and Approaches"
      chapters:
        - NSW_methodology.qmd
        - VIC_methodology.qmd
        - QLD_methodology.qmd
        - SA_methodology.qmd
        - WA_methodology.qmd
        - TAS_methodology.qmd
        - NT_methodology.qmd
        - aclg_note.qmd
    - part: "Key Issues and Debates"
      chapters:
        - historical-context.qmd
        - discussed-issues.qmd
    - part: "Empirical Analysis"
      chapters:
        - simulation_methodology.ipynb
        - 20_perc_min_grant.ipynb
        - 10_perc_min_grant.ipynb
        - no_min_grant.ipynb
    - references.qmd

bibliography: [references.bib, euan_references.bib]
csl: meta/style-manual-australian-government.csl

format:
  html:
    theme:
      - pandoc
      - brand
    code-fold: true
    code-summary: "Show the code"
    code-tools: true
  docx:
    order: 1
    reference-doc: meta/custom-reference-doc.docx
    toc-depth: 1
    fig-align: "center"
    fig-dpi: 600
    df-print: paged
    execute:
      echo: false
      output: true


