project:
  type: book
  output-dir: docs

book:
  title: "A Characterization of the Australian Financial Assistance Grants System"
  author: ["Sreehari Pulickamadhom Sreedhar", "Euan Maclean"]
  date: "7/23/2025"
  chapters:
    - index.qmd
    - intro.qmd
  # - methodology.qmd
    - part: "Jurisdictions and Approaches"
      chapters:
        - historical-context.qmd
        - NSW_methodology.qmd
        - VIC_methodology.qmd
        - QLD_methodology.qmd
        - SA_methodology.qmd
        - WA_methodology.qmd
        - TAS_methodology.qmd
        - NT_methodology.qmd
        - aclg_note.qmd
    - part: "Key Issues and Debates"
      chapters:
        - discussed-issues.qmd
    - part: "Empirical Analysis"
      chapters:
        - simulation_methodology.ipynb
        - 20_perc_min_grant.ipynb
        - 10_perc_min_grant.ipynb
        - no_min_grant.ipynb
    - references.qmd

bibliography: [references.bib, euan_references.bib]

format:
  html:
    theme:
      - pandoc
      - brand
    code-fold: true
    code-summary: "Show the code"
    code-tools: true
  docx:
    order: 1
    reference-doc: custom-reference-doc.docx
    toc-depth: 1
    fig-align: "center"
    fig-dpi: 600
    execute:
      echo: false
      output: true


