---
title: "A note on the Australian Classification of Local Government"
author: Sreehari Pulickamadhom Sreedhar
date: today
references: references.bib
---

The Australian Classification of Local Governments (ACLG) was a system maintained and published by the Department of Infrastructure, Transport, Regional Development, Communications, Sport and the Arts (DITRDCSA) [@ditrdcsaLocalGovernmentNational2022]. The Department is aiming to phase out the ACLG system in favour of the ABS Australian Statistical Geographical System Remoteness classifcation.  


| **Step 1**                               | **Step 2**                                                                                                       | **Step 3**        |             | **Category** | **Alpha** |
|-|-|-|-|-|-|
| **URBAN \(U\)**                          |                                                                                                                  |                   |                  |              |           |
|                                     | Capital City \(CC\)                                                                                              | Not applicable    |                  | 1            | UCC       |
| **Pop\. > 20,000**                       | Metropolitan Developed \(D\) \- Part of an urban centre > 1,000,000 and pop\. density > 600/sq km\.              | Small \(S\)       | up to 30,000     | 2            | UDS       |
|                                     |                                                                                                                  | Medium \(M\)      | 30,001\-70,000   | 3            | UDM       |
|                                     |                                                                                                                  | Large \(L\)       | 70,001\-120,000  | 4            | UDL       |
|                                     |                                                                                                                  | Very large \(VL\) | > 120,000        | 5            | UDV       |
| **Pop\. Density > 30 persons per sq km** | Regional Town/City \(R\) \- Part of an urban centre with population <1,000,000 and predominantly urban in nature | Small             | up to 30,000     | 6            | URS       |
|                                     |                                                                                                                  | Medium            | 30,001\-70,000   | 7            | URM       |
|                                     |                                                                                                                  | Large             | 70,001\-120,000  | 8            | URL       |
|                                     |                                                                                                                  | Very large        | >120,001         | 9            | URV       |
| **>90% of LGA population is urban**      | Fringe \(F\) \- A developing LGA on the margin of a developed or regional urban centre\.                         | Small             | up to 30,000     | 10           | UFS       |
|                                     |                                                                                                                  | Medium            | 30,001\-70,000   | 11           | UFM       |
|                                     |                                                                                                                  | Large             | 70,001\-120,000  | 12           | UFL       |
|                                     |                                                                                                                  | Very large        | >120,001         | 13           | UFV       |
| **RURAL \(R\)**                          |                                                                                                                  |                   |                  |              |           |
|                                     | Significant Growth \(SG\) \- Average annual Population growth > 3%, population > 5,000 and not remote\.          | Not applicable    |                  | 14           | RSG       |
|                                     | Agricultural \(A\)                                                                                               | Small             | Up to 2,000      | 15           | RAS       |
|                                     |                                                                                                                  | Medium            | 2,001\-5,000     | 16           | RAM       |
|                                     |                                                                                                                  | Large             | 5,001,\-10,000   | 17           | RAL       |
|                                     |                                                                                                                  | Very large        | 10,001 to 20,000 | 18           | RAV       |
|                                     | Remote \(T\) \- Situated in a remote locality\.                                                                  | Extra small       | Up to 400        | 19           | RTX       |
|                                     |                                                                                                                  | Small             | 401\-1,000       | 20           | RTS       |
|                                     |                                                                                                                  | Medium            | 1,001–3,000      | 21           | RTM       |
|                                     |                                                                                                                  | Large             | 3,001 to 20,000  | 22           | RTL       |

: {.striped .hover}