---
title: "An introduction to the FA Grants System"
author: "Euan Maclean"
date: today
references: euan_references.bib
---
## Executive Summary 
Local Government is a key provider of services to communities around Australia. Across 538 local governments, $424 Billion worth of community infrastructure is serviced and maintained by councils.  

The Australian Local Government Association (ALGA) is the peak body for councils at the federal level. ALGA represents councils and their interests to the Commonwealth, advocating for greater support for the local government space. 

The last fifteen years have seen a period of declining intergovernmental support for local governments. The Commonwealth Government has slashed financial assistance grants, an essential part of local government funding, and state governments have sought to undermine councils through arbitrary caps on revenue sources and cost shifting. 

Despite this declining support, local governments maintain their position as an important part of providing services to communities. Whether that be supporting communities in the face of bushfires, or planning our cities to house future generations, local governments are a key piece of the puzzle. 


This paper seeks to evaluate one critical aspect of the debate surrounding grants issued by the Commonwealth Government to councils - the minimum grant allocation requirement. 

In order to answer this question, this paper will model the impacts of a change to the minimum grant allocation and its impacts on councils. Our analysis will examine the modelled changes, ascertaining what types of councils are most impacted and performing a qualitative assessment of those impacts. 

## An introduction to FA Grants
Financial Assistance Grants (FA Grants) are a funding mechanism used by the Commonwealth government to distribute funding to Australia's 538 local councils. Every year, the federal government allocates a pull of money to be distributed to councils nation wide. FA Grants are untied, meaning that councils spend money from the FA Grant program autonomously. 

FA Grants are essential to local government, providing critical funding that supports the delivery of community services, infrastructure, and local development projects. Without these grants, many councils - particularly those in regional and rural areas - would struggle to maintain the service levels expected by their communities. 

## Allocation of FA Grants

FA Grants are allocated according to the "Local Government (Financial Assistance) Act" (1995). The FA Grant distribution process consists of three components: a local road network component; a general purpose component; and a per capita minimum grant component. This final component requires every council to be given at least 30% of what their grant would be if distributed on a purely per capita basis. 

Whilst the Commonwealth is responsible for providing FA Grants, it is state government appointed grant commissions which decide how FA Grant money will be distributed, and the more intricate details of the general purpose and roads components. This means councils are assessed differently depending on their state jurisdiction. 

The federal government directs states to allocate FA grants based on two principles: horizontal equilisation and effort neutrality. Horizontal equilisation refers to allocating funds in a way that takes into consideration the differing revenue raising capacities of councils, and effort neutrality directs grant commissions not to punish councils for political or accounting decisions. 

## FA Grants as they stand today

Funding for the FA grant program has evolved since its initial introduction, and the program has not kept up with the expanding role that local councils play. Over the past 30 years, FA grants have been cut from equaling 1% of Commonwealth taxation revenue in 1996, to the present day, where they are worth 0.5% of Commonwealth taxation revenue. 

This decline in real value has been due to a number of factors; including the pausing of the program's indexing between 2014 and 2017. 

The requirement for each council to receive at least 30% of a per capita equivelant grant program is controversial with our members (Australia's 538 local governments). Regional and rural councils see it as a way to funnel money towards urban and peri-urban councils, even though they are not as financially reliant on FA grants as their regional and rural counterparts. This is an understandable perspective, given inner city councils often run in surplus, with a wide range of revenue streams due to high economic activity and a more dense populus.

ALGA holds a long standing view that a more practical way to achieve greater financial sustainability for councils is to increase the size of the pie rather than how it is sliced. This is reflected in ALGA's call for a return to FA Grants being equal to 1% of Commonwealth taxation revenue. 

ALGA has also long suspected that the removal of the 30% minimum allocation would not necessarily benefit the councils most in need, and would likely serve in detriment of those in growth areas. 

## Moving Forward
In this report, we break from this view to consider the impacts of a change to the minimum allocation. We achieve this through modelling the per capita gains and losses of a shift from 30%, considering a set of lower minimum alternatives; and the removal of a minimum allocation in its entirety. 
 
The goal of this analysis is to provide insights into what type of change to the distribution process would optimise the financial sustainability of local governments. 




